package org.codefilarete.jumper.schema.difference;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Set;

import org.codefilarete.jumper.schema.SchemaElementCollector;
import org.codefilarete.jumper.schema.SchemaElementCollector.Schema;
import org.codefilarete.jumper.schema.difference.SchemaDiffer.ComparisonChain.PropertyComparator;
import org.codefilarete.jumper.schema.difference.SchemaDiffer.ComparisonChain.PropertyComparator.PropertyDiff;
import org.codefilarete.reflection.AccessorByMethodReference;
import org.codefilarete.reflection.AccessorDefinition;
import org.codefilarete.stalactite.sql.UrlAwareDataSource;
import org.codefilarete.stalactite.sql.test.HSQLDBInMemoryDataSource;
import org.junit.jupiter.api.Test;

class SchemaDifferTest {
	
	@Test
	void compare() throws SQLException {
		UrlAwareDataSource dataSource = new HSQLDBInMemoryDataSource();
		Connection connection1 = dataSource.getConnection();
		connection1.prepareStatement("create schema REFERENCE").execute();
		connection1.prepareStatement("set schema REFERENCE").execute();
		connection1.prepareStatement("create table A(id BIGINT generated by default as identity, name VARCHAR(200) not null, age float, primary key (id));").execute();
		connection1.prepareStatement("create table B(id BIGINT, aId BIGINT, dummyData VARCHAR(50), primary key (id), constraint fromBtoA foreign key (aId) references A(id));").execute();
		connection1.prepareStatement("create table C(id BIGINT, aId BIGINT, lastname VARCHAR(50), primary key (id), constraint fromCtoA foreign key (aId) references A(id));").execute();
		connection1.prepareStatement("create table D(firstname VARCHAR(50));").execute();
		connection1.prepareStatement("create unique index toto on A(name asc);").execute();
		connection1.prepareStatement("create unique index tata on C(lastname desc);").execute();
		connection1.prepareStatement("create view TUTU as select a.id, a.name, b.dummyData from A a inner join B b on a.id = b.aId;").execute();
		connection1.commit();
		connection1.close();
		
		Connection connection2 = dataSource.getConnection();
		connection2.prepareStatement("create schema COMPARISON").execute();
		connection2.prepareStatement("set schema COMPARISON").execute();
		connection2.prepareStatement("create table A(id BIGINT generated by default as identity, name VARCHAR(200) not null, age float, primary key (id));").execute();
		connection2.prepareStatement("create table B(id BIGINT, aId BIGINT, dummyData VARCHAR(50), primary key (id), constraint fromBtoA foreign key (aId) references A(id));").execute();
		connection2.prepareStatement("create table C(id BIGINT, aId BIGINT, firstname VARCHAR(50), lastname VARCHAR(100), primary key (id));").execute();
		connection2.prepareStatement("create unique index tata on C(lastname asc);").execute();
		connection2.prepareStatement("create view TUTU as select a.id, a.name, b.dummyData from A a inner join B b on a.id = b.aId;").execute();
		connection2.commit();
		connection2.close();
		
		SchemaElementCollector schemaElementCollector = new SchemaElementCollector(dataSource.getConnection().getMetaData());
		schemaElementCollector.withCatalog(null)
				.withSchema("REFERENCE")
				.withTableNamePattern("%");
		Schema ddlElements1 = schemaElementCollector.collect();
		
		schemaElementCollector.withCatalog(null)
				.withSchema("COMPARISON")
				.withTableNamePattern("%");
		Schema ddlElements2 = schemaElementCollector.collect();
		
		SchemaDiffer testInstance = new SchemaDiffer();
		Set<AbstractDiff<?>> diffs = testInstance.compare(ddlElements1, ddlElements2);
		
		System.out.println("----------------------------------------------------------");
		
		System.out.println("Added in " + dataSource.getUrl());
		diffs.stream().filter(d -> d.getState() == State.ADDED).forEach(d -> {
			System.out.println(d.getReplacingInstance());
		});
		System.out.println("Modifications between " + dataSource.getUrl() + " and " +dataSource.getUrl());
		diffs.stream().filter(d -> d.getState() == State.HELD).forEach(d -> {
			if (d instanceof PropertyComparator.PropertyDiff) {
				String propertyName = AccessorDefinition.giveDefinition(new AccessorByMethodReference<>(((PropertyDiff<?, ?>) d).getPropertyAccessor())).getName();
				System.out.println(propertyName +": " + d.getSourceInstance() + " vs " + d.getReplacingInstance());
			}
		});
		System.out.println("Missing in " + dataSource.getUrl());
		diffs.stream().filter(d -> d.getState() == State.REMOVED).forEach(d -> {
			System.out.println(d.getSourceInstance());
		});
	}
	
}