package org.codefilarete.jumper.impl;

import org.codefilarete.jumper.Change;

/**
 * Parent class for {@link Change}s that are known by {@link org.codefilarete.jumper.ChangeSetRunner}, meaning :
 * - their SQL is generated by some {@link org.codefilarete.jumper.ddl.engine.SQLGenerator},
 * - their checksum is computed by {@link org.codefilarete.jumper.ChangeSetRunner}
 * 
 * @author Guillaume Mary
 */
public class SupportedChange implements Change {
	
	private String catalogName;
	
	private String schemaName;
	
	public String getCatalogName() {
		return catalogName;
	}
	
	public void setCatalogName(String catalogName) {
		this.catalogName = catalogName;
	}
	
	public String getSchemaName() {
		return schemaName;
	}
	
	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}
}
